//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HUTDataAccessLayerSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalorieCount
    {
        public int CalorieCountId { get; set; }
        public int PersonId { get; set; }
        public System.DateTime DatetimeEntered { get; set; }
        public int Calories { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
