//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HUTDataAccessLayerSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreezerInventory
    {
        public int FreezerInventoryId { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
