//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HUTDataAccessLayerSQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HomeUseTrackingEntities : DbContext
    {
        public HomeUseTrackingEntities()
            : base("name=HomeUseTrackingEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<CalorieCount> CalorieCounts { get; set; }
        public virtual DbSet<Weight> Weights { get; set; }
        public virtual DbSet<CalorieCountOffDay> CalorieCountOffDays { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<Ingredient> Ingredients { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
        public virtual DbSet<FreezerInventory> FreezerInventories { get; set; }
    }
}
